# bind access to crossplane direct to just the platform team
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: crossplane-admin
# rules:
#   # Full access to everything Crossplane related — for platform team only
#   - apiGroups:
#       - "*.aws.upbound.io"
#       - "*.aws.m.upbound.io"
#       - "pkg.crossplane.io"
#       - "ops.crossplane.io"
#       - "apiextensions.crossplane.io"
#     resources: ["*"]
#     verbs: ["*"]

# bind crossplane-admin to master pipeline SA
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-system-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:masters
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-admin

# bind crossplane-admin to platform team
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psk-admin-crossplane-clusterrolebinding
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: twplatformlabs/platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-admin
