# renames the service account created for the family provider to match default crossplane service account
# created in control-plane-base
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: runtime-upbound-provider-family-aws
spec:
  serviceAccountTemplate:
    metadata:
      name: upbound-provider-family-aws

---
apiVersion: pkg.crossplane.io/v1beta1
kind: ImageConfig
metadata:
  name: runtime-upbound-provider-family-aws
spec:
  matchImages:
    - prefix: xpkg.upbound.io/upbound/provider-family-aws
  runtime:
    configRef:
      name: runtime-upbound-provider-family-aws

# sa renaming for selected AWS provider packagespackages

# upbound-provider-aws-iam
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: runtime-upbound-provider-aws-iam
spec:
  serviceAccountTemplate:
    metadata:
      name: upbound-provider-aws-iam

---
apiVersion: pkg.crossplane.io/v1beta1
kind: ImageConfig
metadata:
  name: runtime-upbound-provider-aws-iam
spec:
  matchImages:
    - prefix: xpkg.upbound.io/upbound/provider-aws-iam
  runtime:
    configRef:
      name: runtime-upbound-provider-aws-iam

# upbound-provider-aws-eks
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: runtime-upbound-provider-aws-eks
spec:
  serviceAccountTemplate:
    metadata:
      name: upbound-provider-aws-eks

---
apiVersion: pkg.crossplane.io/v1beta1
kind: ImageConfig
metadata:
  name: runtime-upbound-provider-aws-eks
spec:
  matchImages:
    - prefix: xpkg.upbound.io/upbound/provider-aws-eks
  runtime:
    configRef:
      name: runtime-upbound-provider-aws-eks







#     - xpkg.upbound.io/upbound/provider-family-aws:v2.5.3
#     - xpkg.upbound.io/upbound/provider-aws-iam:v2.5.3
#     - xpkg.upbound.io/upbound/provider-aws-eks:v2.5.3
#   # -- Define entries for the default managed resource activation policy. If defined, a default MRAP will contain these activations.
#   defaultActivations: ["*"]

# configuration:
#   # -- A list of Configuration packages to install.
#   packages: []

# function:
#   # -- A list of Function packages to install
#   packages:
#     - xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.10.4
#     - xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.12.0