---
apiVersion: platform.psk.io/v1alpha1
kind: XPodIdentityAssociation
metadata:
  name: provider-aws-iam-pod-identity-association
  namespace: crossplane-system
spec:
  serviceAccountName: upbound-provider-aws-iam
  serviceAccountNamespace: crossplane-system
  roleName: psk-crossplane-provider-role

---
apiVersion: platform.psk.io/v1alpha1
kind: XPodIdentityAssociation
metadata:
  name: provider-aws-eks-pod-identity-association
  namespace: crossplane-system
spec:
  serviceAccountName: upbound-provider-aws-eks
  serviceAccountNamespace: crossplane-system
  roleName: psk-crossplane-provider-role
