---
# add eks-pod-identity-association
apiVersion: platform.psk.io/v1alpha1
kind: PodIdentityAssociation
metadata:
  name: provider-aws-eks-pod-identity-association
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: upbound-provider-aws-eks
  serviceAccountNamespace: crossplane-system
  roleName: psk-crossplane-provider-role
