{{- range .Values.functions.packages }}
{{- $parts := splitList "/" . }}
{{- $withVersion := printf "%s-%s" (index $parts 1) (index $parts 2) }}
{{- $name := $withVersion | splitList ":" | first }}
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: {{ $name }}
spec:
  package: {{ . }}
  packagePullPolicy: Always
{{- end }}
