---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: management-node-selector
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
          nodeSelector:
            nodegroup: management-arm-rkt-mng
          tolerations:
            - key: dedicated
              operator: Equal
              value: management
              effect: NoSchedule
