# renames the service accounts created providers and function to a predictable convention, rather the serialized number used by default
{{- $allPackages := concat .Values.providers.packages .Values.functions.packages }}
{{- range $allPackages }}
{{- $parts := splitList "/" . }}
{{- $withVersion := printf "%s-%s" (index $parts 1) (index $parts 2) }}
{{- $name := $withVersion | splitList ":" | first }}
{{- $packageFind := . | splitList ":" | first }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: runtime-{{ $name }}
spec:
  serviceAccountTemplate:
    metadata:
      name: {{ $name }}

---
apiVersion: pkg.crossplane.io/v1beta1
kind: ImageConfig
metadata:
  name: runtime-{{ $name }}
spec:
  matchImages:
    - prefix: {{ $packageFind }}
  runtime:
    configRef:
      name: runtime-{{ $name }}

{{- end}}
