apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: clusterinfos.platform.psk.io
spec:
  scope: Namespaced
  group: platform.psk.io
  names:
    kind: ClusterInfo
    plural: clusterinfos
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sourceNamespace:
                  type: string
                  default: default
                sourceName:
                  type: string
                  default: cluster-info